### ISSUE TITLE
Add an Example for NonlinearConjugateGradient Class

### ISSUE THREAD

**Issue by vulkanzhou** [accord-net/framework#1090] opened 2017-12-04 14:11 UTC
Please add an example for NonlinearConjugateGradient Class.

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: http://accord-framework.net/docs/html/T_Accord_Math_Optimization_NonlinearConjugateGradient.htm

**Comment by cesarsouza** [comment] 2017-12-04 21:37
Duplicate of #982

**Closed by cesarsouza** 2017-12-04 21:37 UTC
