### ISSUE TITLE
Add an Example for HistogramsOfOrientedGradients Class

### ISSUE THREAD

**Issue by DaniloDaniel** [accord-net/framework#915] opened 2017-09-29 03:54 UTC
Please add an example for HistogramsOfOrientedGradients Class.

I'm trying to use HOG for a project and called my Accord .net attention, they could upload a small example to support learning, thanks and greetings.

Help Topic: http://accord-framework.net/docs/html/T_Accord_Imaging_HistogramsOfOrientedGradients.htm#PageHeader

**Comment by blaisexen** [comment] 2017-09-29 06:43
I think this is a pending release,
here are the links,
https://github.com/accord-net/framework/issues/782
https://github.com/accord-net/framework/issues/653

**Comment by cesarsouza** [comment] 2017-09-29 19:46
Hi Danilo,

Thanks for opening the issue. As @blaisexen mentioned, this is already going to be addressed in the next release. This is the example that is going to be added to the documentation:
```csharp
// Let's load an example image, such as Lena,
// from a standard dataset of example images:
var images = new TestImages(path: localPath);
Bitmap lena = images["lena.bmp"];

// Create a new Histogram of Oriented Gradients with the default parameter values:
var hog = new HistogramsOfOrientedGradients(numberOfBins: 9, blockSize: 3, cellSize: 6);

// Use it to extract descriptors from the Lena image:
List<double[]> descriptors = hog.ProcessImage(lena);

// Now those descriptors can be used to represent the image itself, such
// as for example, in the Bag-of-Visual-Words approach for classification.
```

Regards,
Cesar

**Comment by cesarsouza** [comment] 2017-09-29 19:46
Duplicate of #653

**Comment by DaniloDaniel** [comment] 2017-09-30 06:23
thanks!.

**Closed** 2017-09-30 06:24 UTC

**Comment by blaisexen** [comment] 2017-09-30 15:36
@cesarsouza 
is this the way of using the ProcessImage of HistogramsOfOrientedGradients?
OR if not can you change the code according from your thoughts?
```
            var hog = new HistogramsOfOrientedGradients(numberOfBins: 9, blockSize: 3, cellSize: 6);
            var surfBow = BagOfVisualWords.Create(hog, new BinarySplit(10));

            Accord.Math.Random.Generator.Seed = 0;
            surfBow.ParallelOptions.MaxDegreeOfParallelism = 1;
            bow = surfBow.Learn(faceimages.ToArray());

            var kernel = new HistogramIntersection();

            foreach (var faces in listoffaces)
            {
                List<double[]> xfeatureVector = hog.ProcessImage(faces.faceimage);
                for (int s = 0; s <= 9; s++) //USE ONLY 10
                {
                    facevalues.Add(xfeatureVector[s]);
                    faceclassnums.Add(faces.faceclassnum);
                    faceemotname.Add(faces.facekind);
                }
            }
```

**Comment by cesarsouza** [comment] 2017-09-30 16:34
Hi @blaisexen,

```csharp
            var hog = new HistogramsOfOrientedGradients(numberOfBins: 9, blockSize: 3, cellSize: 6);
            var surfBow = BagOfVisualWords.Create(hog, new BinarySplit(10));

            Accord.Math.Random.Generator.Seed = 0;
            surfBow.ParallelOptions.MaxDegreeOfParallelism = 1;
            bow = surfBow.Learn(faceimages.ToArray());
```

In the first part you are creating a BoW with HOG features, which seems correct.

```csharp
            foreach (var faces in listoffaces)
            {
                List<double[]> xfeatureVector = hog.ProcessImage(faces.faceimage);
                for (int s = 0; s <= 9; s++) //USE ONLY 10
                {
                    facevalues.Add(xfeatureVector[s]);
                    faceclassnums.Add(faces.faceclassnum);
                    faceemotname.Add(faces.facekind);
                }
            }
```

But in the second part, I do not know exactly what you are trying to do, so I can't say for sure whether its correct. If you want to extract HOG features from each of the images, then yes it looks correct. But you are not using the BoW at all in this stage, is this intended?

Regards,
Cesar

**Comment by blaisexen** [comment] 2017-09-30 17:04
@cesarsouza 
This application I'm making is a face identification, and I'm using BoW to transform image to double as Feature_Vector, it can identify faces.

The result was good, but not very good, that's why I ask if I used ProcessImage will be much better?

that's why I coded like this: BUT BoW is lost! because I prefer to test the ProcessImage,
now **the REAL question is where or how to use the ProcessImage with BoW?**
because I don't know if using ProcessImage will be more than good.
 
```
            foreach (var faces in listoffaces)
            {
                List<double[]> xfeatureVector = hog.ProcessImage(faces.faceimage);
                for (int s = 0; s <= 9; s++) //USE ONLY 10
                {
                    facevalues.Add(xfeatureVector[s]);
                    faceclassnums.Add(faces.faceclassnum);
                    faceemotname.Add(faces.facekind);
                }
            }
```

>>But you are not using the BoW at all in this stage, is this intended?
for BoW I used like this:

```
            var hog = new HistogramsOfOrientedGradients(numberOfBins: 9, blockSize: 3, cellSize: 6);
            var surfBow = BagOfVisualWords.Create(hog, new BinarySplit(12));

            Accord.Math.Random.Generator.Seed = 0;
            surfBow.ParallelOptions.MaxDegreeOfParallelism = 1;
            bow = surfBow.Learn(faceimages.ToArray());

            foreach (var faces in listoffaces)
            {
                double[] featureVector = (bow as ITransform<Bitmap, double[]>).Transform(faces.faceimage);
                facevalues.Add(featureVector); //faces value
                faceclassnums.Add(faces.faceclassnum); //faces label number/id number
                faceemotname.Add(faces.facekind); //faces names
            }

            var kernel = new HistogramIntersection();
            var svmteacher = new MulticlassSupportVectorLearning<IKernel>()
            {
                Kernel = kernel,
                Learner = (param) =>
- codes here...
-
- codes here...
            ksvm = calibration.Learn(facevalues.ToArray(), faceclassnums.ToArray());
            ksvm.Method = MulticlassComputeMethod.Voting;
```

I identify faces like this:
```
double[] input = (bow as ITransform<Bitmap, double[]>).Transform(GRAYIMAGE);
int kactual = ksvm.Decide(input);
```

**Comment by cesarsouza** [comment] 2017-09-30 18:40
Hi @blaisexen,

The BoW is using ProcessImage behind the scenes to create the bow feature vectors in your first example. If you try to use ProcessImage yourself, with or without the BoW, without understanding how either of them works, it is very likely that you will end up only complicating your code and not achieving anything at all.

> where or how to use the ProcessImage with BoW?

You don't, because BoW is already using ProcessImage in the first place.

Hope it helps,
Cesar

**Comment by blaisexen** [comment] 2017-09-30 20:00
@cesarsouza 
thank you, I understand now! :dancer:
