### ISSUE TITLE
Add an Example for TSNE Class in C#

### ISSUE THREAD

**Issue by jkawalli** [accord-net/framework#791] opened 2017-08-20 11:55 UTC
Please add an example for TSNE Class.

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: http://accord-framework.net/docs/html/T_Accord_MachineLearning_Clustering_TSNE.htm#!

**Comment by cesarsouza** [comment] 2017-10-01 09:23
Duplicate of #411

**Closed by cesarsouza** 2017-10-01 09:23 UTC
Labels: doc-request
