### ISSUE TITLE
Nuget package Accord.Video.FFMPEG v3.0.2 is 32-bit only?

### ISSUE THREAD

**Issue by mod6890325** [accord-net/framework#224] opened 2016-04-12 22:34 UTC
Hello, I got Accord.Video.FFMPEG from Nuget, and it's giving me errors about mismatching architecture (my project is AnyCPU, but runs in 64-bit environment). The question is how can I get 64-bit version of this library (or, ideally, AnyCPU) from Nuget? Do I need to build the whole thing from source myself?

**Comment by tpitman** [comment] 2016-06-26 01:29
I am also trying to use Accord.Video.FFMPEG and have trouble with the dll not being able to load. What is the solution?

**Comment by cesarsouza** [comment] 2016-08-21 12:20
Hello,

Thanks for reporting those issues! Unfortunately there are currently no plans on providing a 64-bit version of Accord.Video.FFMPEG assembly right now. The module originated from AForge.NET's original AForge.Video.FFMPEG library, which was 32-bit only. The problem is that the FFMPEG version that AForge.NET's code had been based upon has since then been obsoleted in favor of new interfaces, which would require far too much work to be updated right now.

It would still be possible to write a new FFMPEG wrapping library using the new FFMPEG interfaces, though, but again, it would require lots of expertise on those new APIs to make it work just right. 

@tpitman Have you installed Accord.Video.FFMPEG using NuGet? If yes, there was a problem in the packaging script that prevented the FFMPEG binaries from being packed together with the .NET assemblies in the NuGet package. It has been fixed in the latest release (3.2).

Regards,
Cesar

**Comment by tpitman** [comment] 2016-08-22 16:19
Thank you. I was using the Accord version and ran into that problem. I will try the new version and see what happens.

Awesome support!

**Comment by tpitman** [comment] 2016-09-01 01:26
I tried 3.2 and still get an error when I try to use the FFMPEG in my app. Is there a sample or tutorial on using it in a WPF Windows 10 app?

**Comment by tpitman** [comment] 2016-09-01 23:34
I just did some debugging and the error I am getting is that FFMPEG is violating OS Loader Lock.

My app works fine capturing video from a device and showing it using the direct show stuff in Accord.

If I simply add a member variable to my class for writing to a file. After adding that suddenly whenever I choose my menu item to start recording that sets everything up I get this exception about os loader lock.

It doesn't even hit my break point in my menu item handler,  so it isn't even getting to any of my setup code.

I am guessing it is the member variable somehow.

**Comment by cesarsouza** [comment] 2016-09-07 18:50
Hi there,

Please let me know if you could answer a few of those questions so we could try to solve this issue!

So first of all, I am sorry I have to ask, but are you sure that you have you set up your project to be 32-bits (instead of the default 64-bits?)

Also, is the compiler giving any warnings in your project?

Then, are you sure the exception is causing problems? For example, does it happen outside of Visual Studio? Please try to double-click your .exe executable instead of running it through Visual Studio and let me know if the problem still persists. If it solves, you can go to Visual Studio's menu bar, go to Debug > Exceptions (or press Ctrl+D, E). Look for 'Managed Debugging Assistants' > Loader Lock and uncheck it.

Finally, this exception actually seems to be more related to DirectX rather than FFMPEG. Do you have DirectX installed, and have you tried to upgrade?

A sample application that uses Accord.Video.FFMPEG to record videos is [Screencast Capture Lite](http://cesarsouza.github.io/screencast-capture/). Can you try to download it and see if you get the same errors?

With best regards,
Cesar

**Comment by tpitman** [comment] 2016-09-07 18:58
Thank you for getting back to me.

I can tell you that I have Windows 10 with whatever DirectX is installed
and kept up to date by default. I am using the Accord DirectShow stuff for
showing the video. When I take out the object that is used to write to a
file, everything works fine. It displays on the screen the video from the
camera. As soon as I add the class to use to save to a file using FFMPEG
that is when the loader lock happens.

I will check all the other things and get back to you.

**Comment by cesarsouza** [comment] 2016-09-07 21:07
Hi there,

I think I have found the issue, and added a few other features in the process of fixing it.

I will put a new pre-release package in NuGet in the next few days (hopefully by tomorrow).

Regards,
Cesar

**Comment by tpitman** [comment] 2016-09-07 21:11
Wow, that is awesome. I will test it as soon as you say it is ready.

**Comment by marcbordoyfs** [comment] 2017-03-02 16:38
Hi

Do you have a release window for the x64 update?

**Comment by cesarsouza** [comment] 2017-03-02 21:31
Hi there,

It should be already available as a pre-release package. Just enable the "include pre-release" checkbox when searching for NuGet packages and add a reference to [Accord.Video.FFMPEG.x64](https://www.nuget.org/packages/Accord.Video.FFMPEG.x64/3.4.2-alpha)

Regards,
Cesar

**Comment by marcbordoyfs** [comment] 2017-03-03 14:09
Yes, I did see that but it seems to be looking for accord.core off the NuGet web site and that web page is down. So I can't install it off of the Nuget package manager.
https://www.nuget.org/packages/Accord.Core/

**Comment by tbnguyen1407** [comment] 2017-03-13 06:59
I have the same problem with missing Accord.Core package on both architectures.

**Comment by debaratidas1994** [comment] 2017-03-21 11:05
I have the same issue with the missing Accord.Core package. Is there anyway we can convert the 32 bit Accord.Video.FFMPEG.dll to a 64 bit one ?

**Comment by sweekly101** [comment] 2017-04-14 07:01
@cesarsouza Accord.Core seems to be missing on NuGet. Do you know when it will be up? Thanks.

**Comment by TharosTheDragon** [comment] 2017-05-12 16:05
Same problem. No Accord.Core.

**Comment by cesarsouza** [comment] 2017-05-21 13:58
Fixed in 3.5.0.

**Closed by cesarsouza** 2017-05-21 13:58 UTC
Labels: pending-release
