### ISSUE TITLE
Bug Found in  Accord.Math.Distance.Levenshtein

### ISSUE THREAD

**Issue by LSGOMYP** [accord-net/framework#232] opened 2016-05-23 12:16 UTC
I found a bug in  Accord.Math.Distance.Levenshtein

the if statement

```
        public static double Levenshtein(string x, string y)
        {
            if (x == null || x.Length == 0)
            {
                if (y == null || y.Length != 0)
                    return 0;
                return y.Length;
            }
            else
            {
                if (y == null || y.Length == 0)
                    return x.Length;
            }
```
in my opinion that the if statement may be like the fowllowing statement
```
       public static double Levenshtein(string x, string y)
        {
            if (x == null || x.Length == 0)
            {
                if (y == null || y.Length == 0)
                    return 0;
                return y.Length;
            }
            else
            {
                if (y == null || y.Length == 0)
                    return x.Length;
            }
```

**Comment by zgrkpnr** [comment] 2016-05-23 12:53
This is not a bug. You are making a suggestion. The above code is perfectly fine.

**Comment by cesarsouza** [comment] 2016-06-03 19:55
You are perfectly right! Many thanks for reporting the issue.

**Comment by cesarsouza** [comment] 2016-08-20 14:33
Fixed on release 3.2.

**Closed by cesarsouza** 2016-08-20 14:33 UTC
