### ISSUE TITLE
Gaussian function is implemented incorrectly.

### ISSUE THREAD

**Issue by zgrkpnr** [accord-net/framework#242] opened 2016-05-31 17:21 UTC
In the Neuro library the Gaussian activation function is implemented incorrectly. 
```
public double Function(double x)
        {
            double y = alpha * x;

            if (y > range.Max)
                return range.Max;
            if (y < range.Min)
                return range.Min;
            return y;
        }
```

This is a linear threshold function, not the Gaussian.

**Comment by cesarsouza** [comment] 2016-06-04 16:09
Thanks for reporting the issue. It is actually a duplicate of #223.

**Closed** 2016-06-04 16:09 UTC
