### ISSUE TITLE
OpenCV HaarCascade XML Compabaility Issue

### ISSUE THREAD

**Issue by nickpateman** [accord-net/framework#118] opened 2015-07-21 19:57 UTC
Hi there,

I'm trying to load a cascade from here,

https://github.com/Itseez/opencv/tree/master/data/haarcascades,

tried
haarcascade_frontalface_default.xml
and
haarcascade_frontalface_alt2.xml

so far but they do not seem compatible.  The Accord.net library is looking for a size element when there isn't one, there is width and height in separate elements, so I added a size element, and then it crashes on this,

```
    /// <summary>
    ///   Checks if the classifier contains tilted (rotated) features
    /// </summary>
    /// 
    private static bool checkTiltedFeatures(HaarCascadeStage[] stages)
    {
        foreach (var stage in stages)
            foreach (var tree in stage.Trees)
                foreach (var node in tree)
                    if (node.Feature.Tilted == true)
                        return true;
        return false;
    }
```

I'd Like to use some cascades for detecting facial features, any idea what the issue is here?  Are there some cascade files somewhere that work with accord.net?  My code to load is as follows,

```
    String path = @"D:\cascades\haarcascade_frontalface_alt2.xml";
    HaarCascade cascade = HaarCascade.FromXml(path);
```

**Comment by anders9ustafsson** [comment] 2015-07-22 06:49
@nickpateman Accord.NET parses according to the older Haar Cascade *Open CV* format. *Open CV* changed the format about two years ago. A quick search through the *Open CV* repository indicates that [this](https://github.com/Itseez/opencv/tree/fdf1996e2ebf25cbc185250404aa9e96d5566302) commit is the last where the older format is used.

There is already an open issue #83 for updating the Haar Cascade parsing to *Open CV*'s current format.

**Comment by cesarsouza** [comment] 2017-07-02 09:55
Duplicate of #83

**Closed by cesarsouza** 2017-07-02 09:55 UTC
