### ISSUE TITLE
Measures.Quartiles() for double Vectors of size 2 is wrong

### ISSUE THREAD

**Issue by hkoestin** [accord-net/framework#736] opened 2017-07-25 11:58 UTC
Hey there,

I just got a strange behavior in my application, which is related to some issue in the accord.net framework I assume. Based on the quartiles of a vector of doubles, I am plotting a box-plot, which is "upside-down" in case of 2 vector elements only.

When calculating the Quartiles for a vector of double values of size 2, the Quartiles are wrong and in potential wrong order. Sending in the values of (20.0, 18.75) into the Measures.Quartiles() extension method with the boolean value of false for the parameter "already sorted", I get wrong results.

I get the following
- Q1: 29.38
- Median: 38.75
- Q3: 28.75

Problem is caused by the else-if statement at the following line: https://github.com/accord-net/framework/blob/4780e21e41cc70e35b659267c77128d2df1c0c33/Sources/Accord.Math/Accord.Statistics/Measures.Vectors.cs#L555

```
            else if (values.Length == 2)
            {
                median = values[0] + values[1];
                q1 = (values[0] + median) / 2.0;
                q3 = (median + values[1]) / 2.0;
                return median;
            }
```

Verification against R implementation:
```
x <- c(20.0, 18.75)
quantile(x)

Results in:
     0%     25%     50%     75%    100%
18.7500 19.0625 19.3750 19.6875 20.0000
```

Issues I see with this implementation: 
- a potentially unsorted vector is not sorted before giving q1 and q3
- the median is wrong (as it is the sum of the first and second value)

One can overcome the issue by simply not using Quartiles() in case of size 2, but just using q1=first and q2=second value.

Kind regards,
Harald

**Comment by hkoestin** [comment] 2017-07-25 12:51
I did some more verification against R and here are the results:
- for 2 elements, I could fix the issue of wrong Quartiles 
- for 3 and more elements, the calculation seems to be wrong after all

I used the following extension method to the existing ones, as I am dealing with nullable doubles:
```c#
internal static class StatisticsExtensions
{
    public static double Median(this IReadOnlyList<double?> values)
    {
        if (!values.Any(x => x.HasValue)) return double.NaN;
        return Median(values.Where(x => x.HasValue).Select(x => x.Value).ToArray());
    }

    public static double Median(this IReadOnlyList<double> values)
    {
        if (!values.Any()) return double.NaN;
        return Measures.Median(values.ToArray());
    }

    public static double Minimum(this IReadOnlyList<double?> values)
    {
        if (!values.Any(x => x.HasValue)) return double.NaN;
        var min = values.Min();
        if (min.HasValue) return min.Value;
        return double.NaN;
    }

    public static double Maximum(this IReadOnlyList<double?> values)
    {
        if (!values.Any(x => x.HasValue)) return double.NaN;
        var max = values.Max();
        if (max.HasValue) return max.Value;
        return double.NaN;
    }

    public static double LowerQuartile(this IReadOnlyList<double?> values)
    {
        if (!values.Any(x => x.HasValue)) return double.NaN;

        // this is a fix for an issue in the Accord.NET Fx, as it does not calculate the
        // Q1 and Q3 values correctly in case of a size-of-2 array
        if (values.Count == 2)
        {
            return (values.Minimum() + values.Median()) / 2.0;
        }

        double q1, q3;
        values.Where(x => x.HasValue).Select(x => x.Value).ToArray().Quartiles(out q1, out q3, false);
        return q1;
    }

    public static double UpperQuartile(this IReadOnlyList<double?> values)
    {
        if (!values.Any(x => x.HasValue)) return double.NaN;

        // this is a fix for an issue in the Accord.NET Fx, as it does not calculate the
        // Q1 and Q3 values correctly in case of a size-of-2 array
        if (values.Count == 2)
        {
            return (values.Median() + values.Maximum()) / 2.0;
        }

        double q1, q3;
        values.Where(x => x.HasValue).Select(x => x.Value).ToArray().Quartiles(out q1, out q3, false);
        return q3;
    }
}
```

And this is the test code, using xUnit:
```c#
public class TestStatisticsExtensions
{
    const int Precision = 3;

    public static IEnumerable<object[]> QuartilesTestValues = new List<object[]>
    {
        new object[] {new double?[] {0.0}, 0.0, 0.0}, // correct
        new object[] {new double?[] {0.0, 1.0}, 0.25, 0.75}, // correct
        new object[] {new double?[] {1.0, 0.0}, 0.25, 0.75}, // correct
        new object[] {new double?[] {1.0, 3.0}, 1.5, 2.5}, // correct
        new object[] {new double?[] {3.0, 1.0}, 1.5, 2.5}, // correct
        new object[] {new double?[] {0.0, 1.0, 2.0}, 0.5, 1.5}, // failing
        new object[] {new double?[] {0.0, 1.0, 2.0, 4.0, 5.4, 3.5, 7.8, 8.9}, 1.75, 6.0}, // failing
        new object[] // failing
        {
            new double?[] {0.0, 1.0, 2.0, 4.0, 5.4, 3.5, 7.8, 8.9, 17.0, 23.78, 98.9, 2.3, 4.5, 6.7, 9.34, 42.42},
            3.2, 11.255
        },
        new object[] // failing
        {
            new double?[] {0.0, 5.4, 2.0, 4.0, 1.0, 3.5, 7.8, 17.0, 8.9, 98.9, 23.78, 2.3, 4.5, 6.7, 42.42, 9.34},
            3.2, 11.255
        }
    };

    [Theory]
    [MemberData(nameof(QuartilesTestValues))]
    public void StatisticsExtensions_return_correct_q1_value_for_vector(double?[] values, double expectedQ1,
        double expectedQ3)
    {
        // Act
        var q1 = values.LowerQuartile();

        // Assert        
        Assert.Equal(expectedQ1, q1, Precision);
    }

    [Theory]
    [MemberData(nameof(QuartilesTestValues))]
    public void StatisticsExtensions_return_correct_q3_value_for_vector(double?[] values, double expectedQ1,
        double expectedQ3)
    {
        // Act
        var q3 = values.UpperQuartile();

        // Assert        
        Assert.Equal(expectedQ3, q3, Precision);
    }
}
```

You can see, that all vectors having more than 3 elements are failing. Sometimes the difference is not really big (e.g. 13.17 vs. 11.225), but still, it is not correct.

Regards, Harald

**Comment by cesarsouza** [comment] 2017-08-01 04:51
Hi Harald,

Thanks a lot for reporting the issue, identifying the cause and providing workable fixes. I will be integrating the fixes into the next release, and will be committing an update and providing a new pre-release in the next few days.

Regards,
Cesar

**Comment by cesarsouza** [comment] 2017-08-03 04:35
Hi Harald,

Indeed, there was indeed an issue with the Quartile method for arrays of size 2. However, regarding the implementation for other sample sizes, I have to say that the current implementation is, in fact, also correct. The point is that there are at least 9 different ways to implement a Quartile function (see this [Wikipedia article for examples](https://en.wikipedia.org/wiki/Quantile#Estimating_quantiles_from_a_sample), and also [R's documentation page for the Quartile function](https://stat.ethz.ch/R-manual/R-devel/library/stats/html/quantile.html)), and, if I am not very mistaken, the framework should be implementing R's type 6 (used by Minitab and by SPSS).

I guess the ideal solution here would be add support for the other methods for computing quartiles. But in the meantime, I will commit a solution for the issue with vectors of length 2.

Regards,
Cesar

**Comment by cesarsouza** [comment] 2017-08-13 14:13
Support for the other methods for computing quartiles have been added with #770 (thanks Ivan!)

**Comment by hkoestin** [comment] 2017-08-21 13:36
Thank you @cesarsouza for applying a fix to this and even pushing further implementations of the quantiles, which are validated against R. Really appreciate this.

Looking forward to the next release, which contains all the fixes and new functions.

**Comment by cesarsouza** [comment] 2017-08-22 19:06
Added in v3.7.0.

**Closed by cesarsouza** 2017-08-22 19:06 UTC
Labels: pending-release
