### ISSUE TITLE
Logistic Regression Properties Score and Probability May Be Reversed

### ISSUE THREAD

**Issue by rpmSportsAnalytics** [accord-net/framework#570] opened 2017-04-30 16:59 UTC
After training a LogisticRegression class, I would like to access the probabilities predicted for a set of test samples. The documentation says to use the Probability(input) method on the class. However, in several models that I am testing, the Probability method returns values for some models in a range of approx. 0 to 10. On the other hand, the Score(input) method returns values that appear to be in the range 0 - 1, as would be expected for a probability. Have the implementation of these methods been interchanged or should the documentation be changed?

I am also testing models using the KernelSupportVectorMachine. In that case, the Probability method returns what appear to be probabilities, and the Score method returns values in the range -x to +x. Also, could the documentation be updated to describe what is the significance or meaning of the values returned by the Score method?

**Comment by cesarsouza** [comment] 2017-06-05 14:24
Hi there,

Sorry for the late reply. I've corrected the Score function to return the hyperplane decision function (basically the linear model underlying the logistic regression model), the Probabilities to return the probabilities (the outputs of the logistic regression model) and the LogLikelihood as the log of the probabilities, as it was intended to be.

Unfortunately, this will be a breaking change for existing users of those classes.

As a rule of thumb, the Score methods are meant to return values between -inf and +inf with zero being the decision point to be taken in case those values are used for classification. The Probabilities are supposed to be between 0 and 1 and, well, reflect actual probabilities. And the LogLikelihood are supposed to be values between 0 and infinity where a decision can be achieved by selecting the maximum between two or more likelihood values, but without a clear decision threshold as in the case of the scores.

The commit will be made available shortly.

Regards,
Cesar

**Comment by cesarsouza** [comment] 2017-07-07 20:24
Fixed in release 3.6.0.

**Closed by cesarsouza** 2017-07-07 20:24 UTC
Labels: pending-release
