### ISSUE TITLE
OutOfMemoryException in Accord.Statistics

### ISSUE THREAD

**Issue by m-imran** [accord-net/framework#133] opened 2015-09-02 11:51 UTC
Hi there,
Excellent stuff you guys have got here. Documentation is great too. I'm using the framework for generating an HMM from a rather large sequence of integers. Actually, there are 900 sequences, and the average length of each sequence is 15000. The number of iterations is set to 100, the number of symbols is 120, and the number of states is 10. Now when I try to estimate the model parameters through BaumWelchLearning, the subject exception is raised at 'run' command. Any hints on how to go ahead with the task will be greatly appreciated.

**Comment by cesarsouza** [comment] 2015-09-02 13:10
Hi there!

Thanks for the good feedback! If you are encountering out of memory exceptions, there are a few things we can try. First of all, please make sure that you are running on a 64-bit system, and that you are compiling your project for .NET4.5 and 64-bits. Also please ensure that you have added the right Accord.NET assemblies to your project (i.e. the ones that also target .NET45 - if you are using NuGet this should be automatic, if you are using the compressed archive version then they will be in the net45 folder).

Then, finally, enable large array support by adding the [following code to the app.config file of your application as instructed in this page](
https://msdn.microsoft.com/en-us/library/hh285054%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396):

```
<configuration>
  <runtime>
    <gcAllowVeryLargeObjects enabled="true" />
  </runtime>
</configuration>
 ```

If it helps, please let me know!

Best regards,
Cesar

**Comment by m-imran** [comment] 2015-09-02 15:09
Thanks a lot for the prompt reply! I'll try all the steps that you advised,
and shall let you know the outcome.
Best regards,

Imran.

**Comment by m-imran** [comment] 2015-09-03 10:37
Hello Cesar

Well I followed your guidelines and voila! the program runs!!! Now it's a
separate issue that my Core i-5 with 4GB RAM is not powerful enough to
handle the calculations, because the system becomes unresponsive and the
hard drive status light is continuously on, showing a lot of disk access.
Memory usage is also above 90%, obviously. If I let it run for, say, four
or five hours, do I risk damaging my hard drive? Just asking some newbie
stuff here, would be thankful for an expert advice.

Regards,

Imran.

**Comment by cesarsouza** [comment] 2015-09-07 10:49
Hi Imran,

I don't think you will risk damaging your hard-drive, but I think it will take an extremely long time to complete if your system is paginating all the time. I think the main memory usage is caused by the Forward and Backward matrices in the HMM estimation algorithm. I suppose it should be possible to write the calculation of those matrices in a more memory efficient manner.

I will leave this ticket open so I can investigate. Thanks for reporting the issue!

**Closed** 2017-01-11 20:05 UTC
