### ISSUE TITLE
Add an Example for VideoFileWriter.WriteAudioFrame Method

### ISSUE THREAD

**Issue by bluehail** [accord-net/framework#808] opened 2017-08-24 09:45 UTC
Please add an example for VideoFileWriter.WriteAudioFrame Method When use WriteAudioFame Method

I'm trying to using save Video and Audio with VideoFilewriter in Accord framework.
but WriteAudioFrame example not found.
Please give me a example code.

Help Topic: http://accord-framework.net/docs/html/M_Accord_Video_FFMPEG_VideoFileWriter_WriteAudioFrame.htm

**Comment by cesarsouza** [comment] 2017-09-28 19:24
Duplicate of #418

**Closed by cesarsouza** 2017-09-28 19:24 UTC
Labels: doc-request
