### ISSUE TITLE
Prediction interval - Accord.Statistics.Models.Regression.LogisticRegression

### ISSUE THREAD

**Issue by BenKester** [accord-net/framework#250] opened 2016-06-15 15:14 UTC
We could really use a method that computes the prediction interval for logistic regression.

As an example, suppose we are predicting the likelihood of the Cubs winning the World Series. The model gives us a result of 20%. What is the 95% confidence interval for the real percent?

R seems to be the only place you can do that right now.

**Comment by cesarsouza** [comment] 2016-08-26 19:57
Thanks for the suggestion! This is actually a duplicate of #81. However, I could never figure out precisely how the prediction interval should be computed, as such, it has never been implemented. If you have a reference on how it is done in R, I would be glad to take a look and attempt to implement it again!

Regards,
Cesar

**Comment by cesarsouza** [comment] 2016-09-14 18:15
So, it seems that an explanation on how to compute prediction intervals for logistic regression [can be found here](https://books.google.es/books?hl=en&lr=&id=Po0RLQ7USIMC&oi=fnd&pg=PR5&dq=logistic+regression+confidence&ots=Do7TpdZiDP&sig=P6Tn8NAartjJ6xqUuCWAX1Bo0iM&redir_esc=y#v=onepage&q=logistic%20regression%20confidence&f=false).

**Comment by BenKester** [comment] 2016-09-14 18:20
Hmm. Interesting.

**Comment by cesarsouza** [comment] 2016-09-15 20:02
Confidence and prediction intervals for logistic and linear regressions will be available in the next release.

**Comment by BenKester** [comment] 2016-09-15 20:04
Thank you very much.

**Comment by cesarsouza** [comment] 2017-01-11 19:48
Integrated in release 3.4.0.

**Closed by cesarsouza** 2017-01-11 19:48 UTC
Labels: duplicate, pending-release
