### ISSUE TITLE
Exception "FileNotFound" 

### ISSUE THREAD

**Issue by MutterOberin** [accord-net/framework#662] opened 2017-06-24 00:27 UTC
Hey! 

I am using Accord, Accord.Video and Accord.Video.FFMPEG x64 and get a strange "FileNotFound" exception on the **"Accord.Video.FFMPEG.x64.dll"** 

The dll is next to the executable so I guess it is missing some dependency. Is there any package on nuget incomplete? 

Using Version 3.5.0

Thanks for any help

**Comment by MutterOberin** [comment] 2017-06-24 12:42
The problem is that the dlls in the build folder of the package were not copied to the output folder.

**Comment by cesarsouza** [comment] 2017-06-29 21:27
Hi there,

Thanks a lot for opening the issue. The .dll files were supposed to be copied automatically by a mechanism I had in place since a long time. I have to check again how it worked and if it is still working. However, I remember that sometimes files might not get copied in case you are doing an upgrade rather than removing the package and reinstalling it again.

I will keep the issue open until I can investigate it. Thanks!

Regards,
Cesar

**Comment by blown302** [comment] 2017-07-07 19:45
I ran into this error as well, it has had to do with the codecs that came with the package but were not being copied to output during build. I pseudo fixed by adding the .dll codecs from below to my project and set it to copy to output when newer. 

`<solution directory>\packages\Accord.Video.FFMPEG.x64.3.5.0\build`

There may be a more elegant solution as it muddies up my project root messy. What is the accepted procedure to get this working?

**Comment by cesarsouza** [comment] 2017-07-07 20:14
Hi @blown302,

Please, may I ask if you were doing an upgrade or a clean install of the Accord.NET FFMPEG package?

Have you ever installed a previous version of Accord.Video.FFMPEG or AForge.Video.FFMPEG in your application before you got this error?

Regards,
cesar

**Comment by blown302** [comment] 2017-07-07 22:06
In a separate project same solution we have the same library version installed. In both cases it was installed fresh. 

I was able to reproduce in a new console app. 

Reproduce Steps:

1. Create new solution with the console app template defaulted to framework 452.
2. Install `Accord.Video.FFMPEG.x64`
3. Instantiate a `VideoFileReader`
4. Run with x64 arch.
5. Wait for Exception in VS (for me it goes to a break mode screen).

Steps to Fix:

1. Right-Click on the project and select Add -> From Existing
2. Navigate to the build directory listed above and select all dlls.
3. In Solution Explorer Right-Click on all the new dlls and select properties -> Copy To Output Directory -> Copy if Newer.
4. Run with x64 Arch.
5. With for program to exit.

![screen shot 2017-07-07 at 3 05 17 pm](https://user-images.githubusercontent.com/1878018/27978675-bc108852-6325-11e7-9015-59fa95cf1cef.png)

**Comment by blown302** [comment] 2017-07-07 22:10
The side effect is I have DLLs in the root of my project. Here is an example of what is happening with this procedure.

<img width="181" alt="screen shot 2017-07-07 at 3 07 37 pm" src="https://user-images.githubusercontent.com/1878018/27978793-676060e2-6326-11e7-8b1e-2bff0681b22c.png">

**Comment by cesarsouza** [comment] 2017-07-08 11:21
Thanks for all the info, I found what was the problem. It will be fixed in the next NuGet packages. I will probably be updating the packages today or tomorrow.

**Comment by blown302** [comment] 2017-07-10 05:49
Thanks Cesar! I'll keep an eye out for the release.

**Comment by cesarsouza** [comment] 2017-08-22 19:34
Fixed in 3.7.0.

**Closed by cesarsouza** 2017-08-22 19:34 UTC
Labels: pending-release
